{% set name = "ldas-tools-frameAPI-swig" %}
{% set version = "2.6.12" %}

# dependencies
{% set ldas_tools_cmake_version = "1.2.3" %}
{% set ldas_tools_frameapi_version = "2.6.6" %}
{% set ldas_tools_framecpp_swig_version = "2.6.14" %}
{% set ldas_tools_ldasgen_swig_version = "2.6.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: 31b2253dab2dc4dbd4d464e91403fbbbd9549b4ebb28fff1a235f6f0681b5fe4

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - make  # [unix]
    - pkg-config  # [unix]
    - swig >=3.0.7,<4.1.0a0
  host:
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
    - ldas-tools-frameapi >={{ ldas_tools_frameapi_version }}
    - ldas-tools-framecpp-swig >={{ ldas_tools_framecpp_swig_version }}
    - ldas-tools-ldasgen-swig >={{ ldas_tools_ldasgen_swig_version }}
  run:
    - ldas-tools-frameapi >={{ ldas_tools_frameapi_version }}
    - ldas-tools-framecpp-swig >={{ ldas_tools_framecpp_swig_version }}
    - ldas-tools-ldasgen-swig >={{ ldas_tools_ldasgen_swig_version }}

test:
  commands:
    - test -f ${PREFIX}/include/frameAPI/LDASframe.i  # [unix]

outputs:
  - name: ldas-tools-frameapi-swig

  - name: python-ldas-tools-frameapi
    script: build-python.sh
    build:
      skip: true  # [python_impl != 'cpython']
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake >=3.6
        - make  # [unix]
        - pkg-config  # [unix]
        - swig >=3.0.7,<4.1.0a0
      host:
        - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
        - ldas-tools-al
        - ldas-tools-al-swig
        - {{ pin_subpackage('ldas-tools-frameapi-swig', exact=True) }}
        - python
      run:
        - python
        - ldas-tools-al
        - ldas-tools-frameapi >={{ ldas_tools_frameapi_version }}
        - {{ pin_subpackage('ldas-tools-frameapi-swig', exact=True) }}
        - python-ldas-tools-framecpp >={{ ldas_tools_framecpp_swig_version }}
        - python-ldas-tools-ldasgen >={{ ldas_tools_ldasgen_swig_version }}
    test:
      imports:
        - LDAStools._LDASframe
    about:
      home: https://wiki.ligo.org/Computing/LDASTools
      dev_url: https://git.ligo.org/computing/ldastools/LDAS_Tools.git
      doc_url: https://computing.docs.ligo.org/ldastools/LDAS_Tools/ldas-tools-frameAPI/
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: Python bindings for the LDAS Tools frame utility library

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/computing/ldastools/LDAS_Tools.git
  doc_url: https://computing.docs.ligo.org/ldastools/LDAS_Tools/ldas-tools-frameAPI/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: SWIG interface for the LDAS Tools frame utility library

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
