travis:
  secure:
    BINSTAR_TOKEN: Q7t3ycnADbN/7asDfAm6XFqRtOU2YRqL5QT+crk0Lp3G6x5gmCTqX82giFlBdHLmaajNmC+LgA3RaAaYdxYvqUcvIli3Zl3GloqEH7dcsDx0e0IIj4lLOPLSX2qY9jO2F3CbX7DELgVNebKZJJEBv2I5NhU8n62rghcCe89FYDr+OMiVjmYZ6b53W2yyx5Nu/UIAGDwPCGvQILdknXPjD9cloFn/lB3iaAGVbIZzMQ/KNOKngx4mc410hiAoDApumEc3IXXpnz6Pe7nIj4QZIv/W+MzflFjA+jVVj3h2vZcfN0gEDSJJApuVdlEUEP62tIuDkEXpveyGoazmmr+V2yR2dt+cJ6+i74NSVBwbPMR05qag9ldXPws+AXdtTin6Fh25zPNfwI6W2foxtODVPJXyoo7XZmnlBlezySAWTeL1UyvsoHprtuz76Z981FM2U6gPUh8OC865BGhQdEr/QDWiMQ0j9xobM1hlpTXRahjbqmH1oEbMJ4ypz4pj31PPjmcI20M3P8COQNp4sBWpREqN2Dk7DJdD4lXWlncn2wbJFD5TEdzNgJwd1HeIXxi1CG9DZfKBfrldhtvoe8L8hIbDN3GSNLiC5WpV4SBGZhukfDipFmEgWsRnxjAJUv6CAhZZsvEoH8rkfoXjuInK150akwBbbB2iidlqjbpl+E8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
